<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="9971" started-at="2021-01-07T16:40:31 IST" finished-at="2021-01-07T16:40:41 IST">
    <groups>
    </groups>
    <test name="Create Customer API Test" duration-ms="6502" started-at="2021-01-07T16:40:31 IST" finished-at="2021-01-07T16:40:37 IST">
      <class name="com.learning.testcases.CreateCustomerTest">
        <test-method status="PASS" signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:0, instance:com.learning.testcases.CreateCustomerTest@625732]" name="validateCreateCustomerAPI" duration-ms="6437" started-at="2021-01-07T16:40:31 IST" data-provider="dp" finished-at="2021-01-07T16:40:37 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=mansi@gmail.com, name=Mansi, description=Mansi - Adding the Third Customer in Framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
        <test-method status="PASS" signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:0, instance:com.learning.testcases.CreateCustomerTest@625732]" name="validateCreateCustomerAPI" duration-ms="5374" started-at="2021-01-07T16:40:31 IST" data-provider="dp" finished-at="2021-01-07T16:40:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=shweta@gmail.com, name=Shweta, description=Shweta - Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
        <test-method status="PASS" signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:0, instance:com.learning.testcases.CreateCustomerTest@625732]" name="validateCreateCustomerAPI" duration-ms="4946" started-at="2021-01-07T16:40:31 IST" data-provider="dp" finished-at="2021-01-07T16:40:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=ritika@gmail.com, name=Ritika, description=Ritika - Adding the fourth Customer in framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
      </class> <!-- com.learning.testcases.CreateCustomerTest -->
    </test> <!-- Create Customer API Test -->
    <test name="Delete Customer API Test" duration-ms="3098" started-at="2021-01-07T16:40:38 IST" finished-at="2021-01-07T16:40:41 IST">
      <class name="com.learning.testcases.DeleteCustomerTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.learning.testcases.DeleteCustomerTest@3059cbc]" name="setup" is-config="true" duration-ms="728" started-at="2021-01-07T16:40:30 IST" finished-at="2021-01-07T16:40:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="validateDeleteCustomerAPI(java.util.Hashtable)[pri:0, instance:com.learning.testcases.DeleteCustomerTest@3059cbc]" name="validateDeleteCustomerAPI" duration-ms="1255" started-at="2021-01-07T16:40:40 IST" data-provider="dp" finished-at="2021-01-07T16:40:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{customer_id=cus_IiMcrJC2xIhlzt}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response doesn't have ID as a field expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response doesn't have ID as a field expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.learning.testcases.DeleteCustomerTest.doValidationUsingJSONObject(DeleteCustomerTest.java:51)
at com.learning.testcases.DeleteCustomerTest.validateDeleteCustomerAPI(DeleteCustomerTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteCustomerAPI -->
        <test-method status="FAIL" signature="validateDeleteCustomerAPI(java.util.Hashtable)[pri:0, instance:com.learning.testcases.DeleteCustomerTest@3059cbc]" name="validateDeleteCustomerAPI" duration-ms="1277" started-at="2021-01-07T16:40:40 IST" data-provider="dp" finished-at="2021-01-07T16:40:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{customer_id=cus_IiMcHqbxIrlnul}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response doesn't have ID as a field expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response doesn't have ID as a field expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.learning.testcases.DeleteCustomerTest.doValidationUsingJSONObject(DeleteCustomerTest.java:51)
at com.learning.testcases.DeleteCustomerTest.validateDeleteCustomerAPI(DeleteCustomerTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteCustomerAPI -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.learning.testcases.DeleteCustomerTest@3059cbc]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-01-07T16:40:41 IST" finished-at="2021-01-07T16:40:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.learning.testcases.DeleteCustomerTest -->
    </test> <!-- Delete Customer API Test -->
  </suite> <!-- Suite -->
</testng-results>
